PROCESSOR 16F877A
INCLUDE <P16F877A.INC>

;DECLARACIÓN DE CONSTANTES
C1 EQU 10H; LA CONSTANTE 1 TENDRÁ VALOR DE 10H
C2 EQU 10H; LA CONSTANTE 2 TENDRÁ VALOR DE 50H
C3 EQU 10H; LA CONSTANTE 3 TENDRÁ VALOR DE 60H

;Asignación de espacio de memoria a variables.
Z1 EQU H'00'; ASIGNACION DE Z1 EN 00H
Z2 EQU H'01'; ASIGNACION DE Z2 EN 01H
Z3 EQU H'02'; ASIGNACION DE Z3 EN 02H
Z4 EQU H'03'; ASIGNACION DE Z4 EN 03H
Z5 EQU H'04'; ASIGNACION DE Z5 EN 04H
Z6 EQU H'05'; ASIGNACION DE Z6 EN 05H
Z7 EQU H'06'; ASIGNACION DE Z7 EN 06H
Z8 EQU H'07'; ASIGNACION DE Z8 EN 07H
Z9 EQU H'08'; ASIGNACION DE Z9 EN 08H
V1 EQU H'21'; ASIGNACION DE V1 EN 21H
V2 EQU H'22'; ASIGNACION DE V2 EN 22H
V3 EQU H'23'; ASIGNACION DE V3 EN 23H
V4 EQU H'24'; ASIGNACION DE V4 EN 24H
V5 EQU H'25'; ASIGNACION DE V5 EN 25H
V6 EQU H'26'; ASIGNACION DE V6 EN 26H
V7 EQU H'27'; ASIGNACION DE V7 EN 27H
V8 EQU H'28'; ASIGNACION DE V8 EN 28H
V9 EQU H'29'; ASIGNACION DE V9 EN 29H
V10 EQU H'30'; ASIGNACION DE V10 EN 30H
V11 EQU H'31'; ASIGNACION DE V11 EN 31H
V12 EQU H'32'; ASIGNACION DE V12 EN 32H

ORG 0
GOTO INICIO
ORG 5

INICIO:
	CLRF PORTA
	CLRF PORTB; LIMPIEZA DE LOS PUERTOS A Y B
	BSF STATUS,RP0
	BCF STATUS, RP1; CAMBIO AL BANCO 1 DE RAM
	MOVWF TRISB;
	CLRF PORTB
	MOVLW H'06'
	MOVWF ADCON1
	MOVLW H'3F'
	MOVWF TRISA
	BCF STATUS, RP0

CICLO:
	MOVLW Z1
	MOVWF V4 
	MOVFW PORTA                 
   	XORWF V4,W                
    BTFSC STATUS,Z             
	GOTO DETENER           

	MOVLW Z2                   
	MOVWF V5                  
	MOVFW PORTA                 
	XORWF V5,W                             
	BTFSC STATUS,Z              
	GOTO GIRO1_HORARIO       

	MOVLW Z3	               
	MOVWF V6                   
	MOVFW PORTA                
	XORWF V6,W                 
	BTFSC STATUS,Z              
	GOTO GIRO1_ANTIHORARIO    

	MOVLW Z4                   
	MOVWF V7                   
	MOVFW PORTA                 
	XORWF V7,W                 
	BTFSC STATUS,Z              
	GOTO GIRO2_HORARIO        

	MOVLW Z5                   
	MOVWF V8                   
	MOVFW PORTA                 
	XORWF V8,W                 
	BTFSC STATUS,Z              
	GOTO GIRO2_ANTIHORARIO    

	MOVLW Z6                   
	MOVWF V9                   
	MOVFW PORTA                 
	XORWF V9,W                 
	BTFSC STATUS,Z              
	GOTO GIRO3_HORARIO            

	MOVLW Z7                   
	MOVWF V10                   
	MOVFW PORTA                 
	XORWF V10,W                 
	BTFSC STATUS,Z              
	GOTO GIRO3_ANTIHORARIO        

	MOVLW Z8                 
	MOVWF V11                   
	MOVFW PORTA                
	XORWF V11,W                 
	BTFSC STATUS,Z              
	GOTO GIRO4_HORARIO  

	MOVLW Z9                   
	MOVWF V12                   
	MOVFW PORTA                 
	XORWF V12,W                 
	BTFSC STATUS,Z              
	GOTO GIRO4_ANTIHORARIO 

DETENER:
	MOVLW 0			    ;MOTORES APAGADOS
    MOVWF PORTB         ;PUERTO B = 0000000
    GOTO CICLO          ;REGRESAR A CICLO

GIRO1_HORARIO:
	MOVLW B'000101'	    ;MOTOR0 APAGADO, MOTOR1 GIROHORARIO
    MOVWF PORTB         
    CALL RETARDO       
    GOTO CICLO          

GIRO1_ANTIHORARIO:   
	MOVLW B'000110'     ;MOTOR0 APAGADO, MOTOR1 GIROANTIHORARIO
	MOVWF PORTB		    
	CALL RETARDO         
	GOTO CICLO          

GIRO2_HORARIO:
	MOVLW B'011000'     ;MOTOR0 GIROHORARIO, MOTOR1 APAGADO
	MOVWF PORTB         
	CALL RETARDO        
	GOTO CICLO          

GIRO2_ANTIHORARIO:
	MOVLW B'101000'     ;MOTOR0 GIROANTIHORARIO, MOTOR1 APAGADO
	MOVWF PORTB			
	CALL RETARDO        
	GOTO CICLO		

GIRO3_HORARIO:
	MOVLW B'011101'     ;MOTOR0 GIROHORARIO, MOTOR1 GIROHORARIO
	MOVWF PORTB			
	CALL RETARDO        
	GOTO CICLO			

GIRO3_ANTIHORARIO:
	MOVLW B'101110'     ;MOTOR0 GIROANTIHORARIO, MOTOR1 GIROANTIHORARIO
	MOVWF PORTB			
	CALL RETARDO        
	GOTO CICLO			

GIRO4_HORARIO:
	MOVLW B'011110'     ;MOTOR0 GIROHORARIO, MOTOR1 GIROANTIHORARIO
	MOVWF PORTB  	
	CALL RETARDO        
	GOTO CICLO			
	
GIRO4_ANTIHORARIO:
	MOVLW B'101101'	    ;MOTOR0 GIROANTIHORARIO, MOTOR1 GIROHORARIO
	MOVWF PORTB			
	CALL RETARDO        
	GOTO CICLO			

RETARDO:
	MOVLW C1            
	MOVWF V1            
TRES:
	MOVWF C2           
	MOVWF V2            	
DOS:
	MOVWF C3            
	MOVWF V3            
UNO:
	DECFSZ V3           
	GOTO UNO            
	DECFSZ V2           
	GOTO DOS            
	DECFSZ V1           
	GOTO TRES           
	RETURN              
	END                 ;FIN DEL PROGRAMA